
modLoader = "javafml"

loaderVersion = "[40,)"

license = "MIT"

[[mods]]
modId = "lagremoval"
version= "${version}"
displayName = "LagRemoval"
authors = "X_Niter"
description = '''
Clean up the Entity lag on your server at set intervals
'''

[[dependencies.lagremoval]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.lagremoval]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "SERVER"
